### PR TITLE
Add safe navigation accesses to the language

### PR DESCRIPTION
**Pull request by alexnask**
This may have a couple of kinks, I'll write a bunch of tests for it tomorrow.  

Also, the new nq_\* overloads need to be added to OocListener, will be taken care of.

### CODE REVIEW

**Comment by thomasfanell** [comment]
It appears that this only works with variables/fields?

**Comment by alexnask** [comment]
@thomasfanell  

This works on many things, Access is defined as:  

``` c
Access =  ((ident:IDENT_CORE { tokenPos; } '&' ![&=] - { core->token[1] += 1; $$=l=nq_onAddressOf(core->this, nq_onVarAccess(core->this, NULL, ident)); }) # special case: blah& is always a reference. blah & blih is a binary and.
          | l:Value)
                ((
                    - '[' - { tokenPos; nq_onArrayAccessStart(core->this, l); }
                             index:Expr - { nq_onStatement(core->this, index); }
                   (',' WS index:Expr - { nq_onStatement(core->this, index); })*
                    - CLOS_SQUAR ~{ throwError(NQE_EXP_CLOSING_SQUAR, "Malformed array access! Expected ']' to end array access.\n"); }
                    - { $$=l=nq_onArrayAccessEnd(core->this); }

                 )
                | - call:FunctionCall                   { nq_onFunctionCallExpr(core->this, call, l); $$=l=call; }
                | - r:IDENT_CORE { tokenPos; $$=l=nq_onVarAccess(core->this, l, r); }
                | - AS_KW { tokenPos; } -  r:Type       { $$=l=nq_onCast(core->this, l, r); }
                | '&' ![&=] - &([ \t\r\n;,)}] | ']')    { core->token[1] += 1; $$=l=nq_onAddressOf(core->this, l); }
                | '@'                                    { $$=l=nq_onDereference(core->this, l); }
                | - call:FunctionCallNoname             { $$=l=nq_onFunctionCallCombo(core->this, call, l); }
                )* 
```

Quick function call example:  

``` ooc
f: func -> String {
    null
}

buff := f() $ _buffer ?? Buffer new(512)
```

**Comment by alexnask** [comment]
Actually, I think "most things" would be accurate :)

**Comment by thomasfanell** [comment]
Perhaps i've yet to fully understand how this works, but here is a quick mock-up example to illustrate what I mean:

``` ooc
Polynomial: class {
    m_derivative: Polynomial
    derivative ::= this m_derivative
    init: func
    differentiate: func -> Polynomial {
        // differentiate and return result
        this m_derivative
    }
}

somePolynomial := Polynomial new()
thirdDerivative: Polynomial

// error: 'source_Main__Polynomial' has no member named 'derivative'
thirdDerivative = somePolynomial $ derivative $ derivative $ derivative

// error Expected include, import, statement or declaration
thirdDerivative = somePolynomial $ differentiate() $ differentiate() $ differentiate()

// This works
thirdDerivative = somePolynomial $ m_derivative $ m_derivative $ m_derivative

```

I would expect that all three of these would work, but that is obviously not the case. What am I missing? :-)

**Comment by alexnask** [comment]
Ah, I see, I thought you were talking about the grammar since you commented on NagaQueen.  

Case number one should indeed work, I am surprised it doesn't (I would expect rock to replace the access with the property call after the safe navigation has been replaced with a ternary expression), if you could open an issue on rock I would be grateful.  

As for number two, this is by design, I think allowing anything but an access after the expression would quickly become really confusing.

**Comment by thomasfanell** [comment]
Oh, shoot! Sorry for posting in the wrong repo. I'll create an issue, thank you!

**Pull request merged**
